version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: InventrySystem/Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ConnectionStrings__sqlConnection: "Server=db;Database=InventrySystemDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true"

  frontend:
    build:
      context: ./InventryUI
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mssql_data:
